Vagrant.configure(2) do |config|
  config.vm.network "forwarded_port", guest: 80, host: 8080
	config.vm.define "devops-box" do |devbox|
        devbox.vm.box = "ubuntu/trusty64"
		#devbox.vm.box = "centos/7"
    		#devbox.vm.network "private_network", ip: "192.168.199.9"
    		devbox.vm.hostname = "devops-box"
      		devbox.vm.provision :ansible do |ansible|
            ansible.playbook = "provisioner/ansible/playbook.yml"
          end
    		devbox.vm.provider "virtualbox" do |v|
    		  v.memory = 4096
    		  v.cpus = 2
              v.name = "DevOpsBox"
    		end
	end
end